version: '3.8'
services:
  dev-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: weather-monster
    ports:
      - 5432:5432
    networks:
      - localhost
  test-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: weather-monster
    ports:
      - 5435:5432
    networks:
      - localhost
networks:
  localhost:
